import streamlit as st
import pandas as pd
import matplotlib.pyplot as plt

st.title("Delivery Optimization Dashboard")
st.write(
    """
    This dashboard visualizes the results of the delivery optimization system.
    Deliveries are assigned to three agents using a greedy algorithm that balances
    the total travel distance among agents while prioritizing high-priority deliveries.
    """
)
data = pd.read_csv("output/delivery_plan.csv")
st.header("Delivery Plan")
st.write("This table shows the final delivery assignments generated by the optimization algorithm.")
st.dataframe(data)
st.header("Total Deliveries")
total_deliveries = len(data)
st.write("Number of deliveries processed:", total_deliveries)
st.header("Deliveries Handled by Each Agent")
agent_counts = data["Assigned_Agent"].value_counts()
st.write(agent_counts)
st.header("Total Distance Handled by Each Agent")
agent_distance = data.groupby("Assigned_Agent")["Distance"].sum()
st.write(agent_distance)
st.header("Distance Distribution Across Agents")
fig, ax = plt.subplots()
agent_distance.plot(kind="bar", ax=ax)
ax.set_xlabel("Delivery Agents")
ax.set_ylabel("Total Distance")
ax.set_title("Total Distance Handled by Each Agent")
st.pyplot(fig)
st.header("Average Distance per Delivery")
avg_distance = data.groupby("Assigned_Agent")["Distance"].mean()
st.write(avg_distance)
st.write("Dashboard generated for the Delivery Optimization Project.")